FROM ubuntu:22.04 as builder

ENV TZ=America/US
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONFAULTHANDLER=1

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        build-essential \
        ninja-build \
        postgresql-client-14 \
        python3-pip \
        python3-venv \
        python3-dev \
        libgflags-dev && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir conan==2.15.0 'cmake<4.0' && \
     conan profile detect --force && \
     conan remote add otterbrix http://conan.otterbrix.com

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

WORKDIR /app/build
COPY ./conanfile.py ./conanfile.py
RUN conan install conanfile.py --build=missing -s build_type=Release -s compiler.cppstd=gnu20

WORKDIR /app
COPY ./include ./include
COPY ./common ./common
COPY ./logical_replication ./logical_replication
COPY ./otterbrix ./otterbrix
COPY ./postgres ./postgres
COPY ./main.cpp ./main.cpp
COPY ./CMakeLists.txt ./CMakeLists.txt
COPY ./wait-for-postgres.sh ./wait-for-postgres.sh

RUN chmod +x ./wait-for-postgres.sh

WORKDIR /app/build

RUN cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE=./build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release && \
    cmake --build . --target diplom -- -j $(nproc)

CMD [ "./diplom" ]