version: '3.1'
---
services:
  postgres:
    image: postgres:latest
    command: -c config_file=/etc/postgresql.conf
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
