version: '3.1'
---
services:
  postgres:
    container_name: postgres
    image: postgres:14
    command: -c config_file=/etc/postgresql.conf
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_init/init:/docker-entrypoint-initdb.d
      - ./postgres_init/postgresql.conf:/etc/postgresql.conf

  app:
    build:
      context: .
      dockerfile: Dockerfile-service
    container_name: otterstax_app
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
    entrypoint: ["../wait-for-postgres.sh", "postgres", "./diplom"]

  generator:
    build:
      context: .
      dockerfile: Dockerfile-generate
    container_name: generate_container
    depends_on:
      - app
      - postgres
